# Application Configuration
server:
  port: 8080
  error:
    # Since SpringBoot 2.3 message response is hidden to avoid leaking sensitive information
    include-message: always
    include-binding-errors: always
    forward-headers-strategy: framework

# To see H2 Console in Browser
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  application:
    name: customer-service
  h2:
    console:
      enable: true

  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
    initialization-mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        use_sql_comments: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-5%p} %m%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /customers/openapi
  swagger-ui:
    path: /customers/swagger
