# This is the configuration to call config server without bootstrap
spring:
  application:
    name: shopping-service
  config:
    # Remove the optional to force the config client fail if it can't connect
    #import: optional:configserver:http://localhost:8081
    import: configserver:http://config-service:8081
  cloud:
    config:
      username: root
      password: s3cr3t@
  boot:
    admin:
      client:
        url: http://admin-service:8086